Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -11,6 +11,7 @@ GIT_SSH_KEY1=$(<"$ENV_DIR/GIT_SSH_KEY1")
 GIT_SSH_KEY2=$(<"$ENV_DIR/GIT_SSH_KEY2")
 GIT_SSH_KEY3=$(<"$ENV_DIR/GIT_SSH_KEY3")
 GIT_SSH_KEY4=$(<"$ENV_DIR/GIT_SSH_KEY4")
+GIT_SSH_KEY4=$(<"$ENV_DIR/GIT_SSH_KEY5")
 
 if [[ -z $GIT_REPO_URL ]]; then
     echo "Did you forget to set GIT_REPO_URL?"
@@ -31,6 +32,10 @@ if [[ -z $GIT_SSH_KEY3 ]]; then
 fi
 if [[ -z $GIT_SSH_KEY4 ]]; then
     echo "Did you forget to set GIT_SSH_KEY4?"
+    exit 1
+fi
+if [[ -z $GIT_SSH_KEY5 ]]; then
+    echo "Did you forget to set GIT_SSH_KEY5?"
     exit 1
 fi
 
@@ -69,6 +74,10 @@ cp "$ENV_DIR/GIT_SSH_KEY3" ~/.ssh/id_rsa3
 echo >> ~/.ssh/id_rsa3
 chmod 600 ~/.ssh/id_rsa3
 #ssh-add ~/.ssh/id_rsa3
+cp "$ENV_DIR/GIT_SSH_KEY5" ~/.ssh/id_rsa5
+echo >> ~/.ssh/id_rsa5
+chmod 600 ~/.ssh/id_rsa5
+#ssh-add ~/.ssh/id_rsa5
 echo "-----> Installed SSH keys for submodules repos"
 
 # MONSTRUOZ1 repo
@@ -109,6 +118,14 @@ echo "   StrictHostKeyChecking no" >> ~/.ssh/config
 echo "   UserKnownHostsFile /dev/null" >> ~/.ssh/config
 echo "   User git" >> ~/.ssh/config
 echo "   IdentityFile ~/.ssh/id_rsa3" >> ~/.ssh/config
+echo "   LogLevel ERROR" >> ~/.ssh/config
+#Host somealiasname somehost.example.org
+echo "Host github.com-fintgbot" >> ~/.ssh/config
+echo "   HostName github.com" >> ~/.ssh/config
+echo "   StrictHostKeyChecking no" >> ~/.ssh/config
+echo "   UserKnownHostsFile /dev/null" >> ~/.ssh/config
+echo "   User git" >> ~/.ssh/config
+echo "   IdentityFile ~/.ssh/id_rsa5" >> ~/.ssh/config
 echo "   LogLevel ERROR" >> ~/.ssh/config
 
 echo "-----> Installed SSH keys for main repo"
